name: Publish and Release

on:
  pull_request:
    branches: [main]

jobs:
  release-publish:
    name: Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.20.3
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - name: Install with pnpm
        run: pnpm install
      - name: Install semantic-release extra plugins
        run: pnpm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
